typedef sdf_fdm_u16_t sdf_fdm_opcode_t;

#define SDF_FDM_OPCODE_TERTIARY( \
  parameter_a_primitive,         \
  parameter_b_primitive,         \
  parameter_c_primitive,         \
  return_primitive,              \
  id                             \
) (                              \
  parameter_a_primitive * 16384  \
  + parameter_b_primitive * 4096 \
  + parameter_c_primitive * 1024 \
  + return_primitive * 256       \
  + id                           \
)

#define SDF_FDM_OPCODE_BINARY( \
  parameter_a_primitive,       \
  parameter_b_primitive,       \
  return_primitive,            \
  id                           \
) SDF_FDM_OPCODE_TERTIARY(     \
  parameter_a_primitive,       \
  parameter_b_primitive,       \
  SDF_FDM_PRIMITIVE_NONE,      \
  return_primitive,            \
  id                           \
)

#define SDF_FDM_OPCODE_UNARY( \
  parameter_a_primitive,      \
  return_primitive,           \
  id                          \
) SDF_FDM_OPCODE_BINARY(      \
  parameter_a_primitive,      \
  SDF_FDM_PRIMITIVE_NONE,     \
  return_primitive,           \
  id                          \
)

#define SDF_FDM_OPCODE_NULLARY( \
  return_primitive,             \
  id                            \
) SDF_FDM_OPCODE_UNARY(         \
  SDF_FDM_PRIMITIVE_NONE,       \
  return_primitive,             \
  id                            \
)

#define SDF_FDM_OPCODE_UNARY_NEGATE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 0)
#define SDF_FDM_OPCODE_UNARY_NOT SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, 1)
#define SDF_FDM_OPCODE_UNARY_SINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 2)
#define SDF_FDM_OPCODE_UNARY_COSINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 3)
#define SDF_FDM_OPCODE_UNARY_TANGENT SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 4)
#define SDF_FDM_OPCODE_UNARY_ARC_SINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 5)
#define SDF_FDM_OPCODE_UNARY_ARC_COSINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 6)
#define SDF_FDM_OPCODE_UNARY_ARC_TANGENT SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 7)
#define SDF_FDM_OPCODE_UNARY_HYPERBOLIC_SINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 8)
#define SDF_FDM_OPCODE_UNARY_HYPERBOLIC_COSINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 9)
#define SDF_FDM_OPCODE_UNARY_HYPERBOLIC_TANGENT SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 10)
#define SDF_FDM_OPCODE_UNARY_HYPERBOLIC_ARC_SINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 11)
#define SDF_FDM_OPCODE_UNARY_HYPERBOLIC_ARC_COSINE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 12)
#define SDF_FDM_OPCODE_UNARY_HYPERBOLIC_ARC_TANGENT SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 13)
#define SDF_FDM_OPCODE_UNARY_ABSOLUTE SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 14)
#define SDF_FDM_OPCODE_UNARY_SQUARE_ROOT SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 15)
#define SDF_FDM_OPCODE_UNARY_FLOOR SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 16)
#define SDF_FDM_OPCODE_UNARY_CEILING SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 17)
#define SDF_FDM_OPCODE_UNARY_NATURAL_LOGARITHM SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 18)
#define SDF_FDM_OPCODE_UNARY_LOGARITHM_10 SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 19)
#define SDF_FDM_OPCODE_UNARY_NATURAL_POWER SDF_FDM_OPCODE_UNARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 20)

#define SDF_FDM_OPCODE_BINARY_ADD SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 0)
#define SDF_FDM_OPCODE_BINARY_SUBTRACT SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 1)
#define SDF_FDM_OPCODE_BINARY_MULTIPLY SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 2)
#define SDF_FDM_OPCODE_BINARY_DIVIDE SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 3)
#define SDF_FDM_OPCODE_BINARY_POWER SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 4)
#define SDF_FDM_OPCODE_BINARY_MODULO SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 5)
#define SDF_FDM_OPCODE_BINARY_AND SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, 6)
#define SDF_FDM_OPCODE_BINARY_OR SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, 7)
#define SDF_FDM_OPCODE_BINARY_EQUAL SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, 8)
#define SDF_FDM_OPCODE_BINARY_INEQUAL SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, 9)
#define SDF_FDM_OPCODE_BINARY_ARC_TANGENT SDF_FDM_OPCODE_BINARY(SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 10)

#define SDF_FDM_OPCODE_TERNARY_CONDITIONAL_BOOLEAN SDF_FDM_OPCODE_TERNARY(SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_BOOLEAN, 0)
#define SDF_FDM_OPCODE_TERNARY_CONDITIONAL_FLOAT SDF_FDM_OPCODE_TERNARY(SDF_FDM_PRIMITIVE_BOOLEAN, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, SDF_FDM_PRIMITIVE_FLOAT, 1)
