typedef sdf_fdm_u16_t sdf_fdm_opcode_t;
#define SDF_FDM_OPCODE_MAX SDF_FDM_U16_MAX
#define SDF_FDM_OPCODE_RANGE SDF_FDM_U16_RANGE

typedef sdf_fdm_u8_t sdf_fdm_opcode_region_t;
#define SDF_FDM_OPCODE_REGION_MAX SDF_FDM_U8_MAX
#define SDF_FDM_OPCODE_REGION_RANGE SDF_FDM_U8_RANGE

#define SDF_FDM_OPCODE_CONSTANT(primitive) (primitive)
#define SDF_FDM_OPCODE_UNARY(opcode) SDF_FDM_OPCODE_CONSTANT(SDF_FDM_PARAMETER_RANGE + opcode)
#define SDF_FDM_OPCODE_BINARY(opcode) SDF_FDM_UNARY(SDF_FDM_OPCODE_RANGE + opcode)
#define SDF_FDM_OPCODE_TERNARY(opcode) SDF_FDM_BINARY(SDF_FDM_OPCODE_RANGE + opcode)

#define SDF_FDM_OPCODE_CONSTANT_FLOAT SDF_FDM_OPCODE_CONSTANT(SDF_FDM_TYPE_FLOAT)

#define SDF_FDM_UNARY_NEGATE SDF_FDM_UNARY(0)
#define SDF_FDM_UNARY_NOT SDF_FDM_UNARY(1)
#define SDF_FDM_UNARY_SINE SDF_FDM_UNARY(2)
#define SDF_FDM_UNARY_COSINE SDF_FDM_UNARY(3)
#define SDF_FDM_UNARY_TANGENT SDF_FDM_UNARY(4)
#define SDF_FDM_UNARY_ARC_SINE SDF_FDM_UNARY(5)
#define SDF_FDM_UNARY_ARC_COSINE SDF_FDM_UNARY(6)
#define SDF_FDM_UNARY_ARC_TANGENT SDF_FDM_UNARY(7)
#define SDF_FDM_UNARY_HYPERBOLIC_SINE SDF_FDM_UNARY(8)
#define SDF_FDM_UNARY_HYPERBOLIC_COSINE SDF_FDM_UNARY(9)
#define SDF_FDM_UNARY_HYPERBOLIC_TANGENT SDF_FDM_UNARY(10)
#define SDF_FDM_UNARY_HYPERBOLIC_ARC_SINE SDF_FDM_UNARY(11)
#define SDF_FDM_UNARY_HYPERBOLIC_ARC_COSINE SDF_FDM_UNARY(12)
#define SDF_FDM_UNARY_HYPERBOLIC_ARC_TANGENT SDF_FDM_UNARY(13)
#define SDF_FDM_UNARY_ABSOLUTE SDF_FDM_UNARY(14)
#define SDF_FDM_UNARY_SQUARE_ROOT SDF_FDM_UNARY(15)
#define SDF_FDM_UNARY_FLOOR SDF_FDM_UNARY(16)
#define SDF_FDM_UNARY_CEILING SDF_FDM_UNARY(17)
#define SDF_FDM_UNARY_NATURAL_LOGARITHM SDF_FDM_UNARY(18)
#define SDF_FDM_UNARY_LOGARITHM_10 SDF_FDM_UNARY(19)
#define SDF_FDM_UNARY_NATURAL_POWER SDF_FDM_UNARY(20)

#define SDF_FDM_BINARY_ADD SDF_FDM_BINARY(0)
#define SDF_FDM_BINARY_SUBTRACT SDF_FDM_BINARY(1)
#define SDF_FDM_BINARY_MULTIPLY SDF_FDM_BINARY(2)
#define SDF_FDM_BINARY_DIVIDE SDF_FDM_BINARY(3)
#define SDF_FDM_BINARY_POWER SDF_FDM_BINARY(4)
#define SDF_FDM_BINARY_MODULO SDF_FDM_BINARY(5)
#define SDF_FDM_BINARY_AND SDF_FDM_BINARY(6)
#define SDF_FDM_BINARY_OR SDF_FDM_BINARY(7)
#define SDF_FDM_BINARY_EQUAL SDF_FDM_BINARY(8)
#define SDF_FDM_BINARY_INEQUAL SDF_FDM_BINARY(9)
#define SDF_FDM_BINARY_ARC_TANGENT SDF_FDM_BINARY(10)

#define SDF_FDM_TERNARY_CONDITIONAL_BOOLEAN SDF_FDM_TERNARY(0)
#define SDF_FDM_TERNARY_CONDITIONAL_FLOAT SDF_FDM_TERNARY(1)
