typedef sdf_fdm_u8_t sdf_fdm_primitive_t;
#define SDF_FDM_PRIMITIVE_MAX 3
#define SDF_FDM_PRIMITIVE_RANGE 4
#define SDF_FDM_PRIMITIVE_NONE 0
#define SDF_FDM_PRIMITIVE_BOOLEAN 1
#define SDF_FDM_PRIMITIVE_FLOAT 2
#define SDF_FDM_PRIMITIVE_RESERVED 3
